version: "3.9"

services:
  onetimeshare:
    # Directly use the pre-built image from the registry
    image: ghcr.io/volkanoezdemir/onetimeshare:${APP_VERSION:-latest}
    ports:
      # Expose the onetimeshare on host port 8080, mapping to the container's port 80 (Nginx)
      - "8080:80"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      # Health check for Nginx serving the frontend (port 80) and Backend (port 8000)
      test: ["CMD", "/usr/bin/curl", "-f", "http://localhost/", "&&", "/usr/bin/curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      # In production, API calls are relative to the same host, so VITE_API_BASE_URL is not needed.
      # If VITE_PUBLIC_HOST is needed by the frontend at runtime, uncomment and set it here:
      # - VITE_PUBLIC_HOST=${VITE_PUBLIC_HOST}

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  redis_data: