services:
  onetimeshare:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-f", "http://localhost/", "&&", "/usr/bin/curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  redis_data: